// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using GraphicsEmployee;
//
//    var employees = Employees.FromJson(jsonString);

namespace GraphicsEmployee
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Employees
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("salary")]
        public long Salary { get; set; }

        [JsonProperty("position")]
        public string Position { get; set; }

        override public string ToString()
        {
            return Name;
        }
    }

    public partial class Employees
    {
        public static Employees[] FromJson(string json) => JsonConvert.DeserializeObject<Employees[]>(json, GraphicsEmployee.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Employees[] self) => JsonConvert.SerializeObject(self, GraphicsEmployee.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
